#!/bin/bash
echo "======================================"
echo "   RealPaperTrading - Quick Deploy"
echo "======================================"
echo ""
echo "Step 1: Initialize Git..."
git init

echo ""
echo "Step 2: Add all files..."
git add .

echo ""
echo "Step 3: Create initial commit..."
git commit -m "Initial commit: RealPaperTrading Simulator with InstantDB"

echo ""
echo "✅ Git repository ready!"
echo ""
echo "======================================"
echo "   NEXT STEPS (Manual):"
echo "======================================"
echo ""
echo "1. Create GitHub repository at: https://github.com/new"
echo "   Name: realpapertrading-simulator"
echo ""
echo "2. Run these commands:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/realpapertrading-simulator.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Deploy to Vercel at: https://vercel.com/new"
echo "   - Import your GitHub repository"
echo "   - Add environment variables:"
echo "     * NEXT_PUBLIC_TWELVE_DATA_API_KEY=6d8e110e8f884e4782c3af257e57f7df"
echo "     * NEXT_PUBLIC_INSTANT_APP_ID=959b5976-79ee-4df6-83f4-2834e81a390e"
echo ""
echo "4. Click Deploy!"
echo ""
echo "======================================"
